name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ secrets.DOMAIN_STAGING }}
      STACK_NAME: ${{ secrets.STACK_NAME_STAGING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync repository to target directory
        run: |
          rsync -a --delete ${{ github.workspace }}/ /home/ubuntu/devi_crm/

      - name: Build Docker containers
        run: |
          cd /home/ubuntu/devi_crm
          docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} build

      - name: Restart Docker containers
        run: |
          cd /home/ubuntu/devi_crm
          docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} up 

