name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
      
    env:
      ENVIRONMENT: staging
      DOMAIN: ${{ secrets.DOMAIN_STAGING }}
      STACK_NAME: ${{ secrets.STACK_NAME_STAGING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: devi_crm  # Checkout into a subdirectory called devi_crm

      - name: Pull latest changes
        run: |
          cd $GITHUB_WORKSPACE/devi_crm
          git pull origin main  # Ensure the latest changes are pulled

      - name: Build Docker containers
        run: |
          cd $GITHUB_WORKSPACE/devi_crm
          docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} build

      - name: Restart Docker containers
        run: |
          cd $GITHUB_WORKSPACE/devi_crm
          docker compose -f docker-compose.yml --project-name ${{ secrets.STACK_NAME_STAGING }} up -d  # Restart containers in detached mode
